- name: checkout dkg
  git:
    repo: '{{ git_repo }}'
    dest: '{{ dkg_home }}'
    version: '{{ git_branch }}'
    force: true
    accept_hostkey: yes
  tags:
    - build-chain
    - rebuild-chain

- name: compile tangle-collator node
  command:
    cmd: '{{ cargo_bin }} +nightly build --release -p tangle-collator'
    chdir: '{{ tangle_home }}'
  async: 3600
  poll: 0
  register: tangle
  tags:
    - build-chain
    - rebuild-chain

- name: compile tangle-node - check async status
  async_status: jid={{ tangle.ansible_job_id }}
  register: job_result
  until: job_result.finished
  retries: 1000
  delay: 10
  tags:
    - build-chain
    - rebuild-chain

- name: change tangle-node bin owner to tangle-node
  file:
    path: '{{ tangle_bin }}'
    owner: tangle
    group: tangle
    mode: '0744'
    state: file
  become: true
  tags:
    - build-chain
