
- name: Stop tangle collator service
  become: true
  systemd:
    name: tangle-collator.service
    state: stopped

- name: Bring chain spec
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: "{{ tangle_user_home }}/resources/testnet/template-local-raw.json"
    dest: "{{ tangle_user_home }}/resources/testnet/template-local-raw.json"
    owner: tangle
    mode: '0644'

- name: Purge chain
  become: true
  shell: |
    set -o pipefail
    {{ tangle_bin }} purge-chain -y --chain "{{ tangle_user_home }}/resources/testnet/template-local-raw.json" --base-path {{ chain_data_dir }}  --database paritydb
  args:
    executable: /bin/bash
  changed_when: False

- name: Reinstall Tangle collator systemd unit file (collator node)
  template: src=tangle-collator-node.j2 dest=/etc/systemd/system/tangle-collator.service
  become: true
  when: "'collator_node' in group_names"
  vars:
    peers: "{{ groups['collator_node'] }}"
  tags:
    collator-node-service

- name: Start collator service
  become: true
  systemd:
    name: tangle-collator.service
    state: started
    daemon_reload: yes