
- name: Stop tangle standalone service
  become: true
  systemd:
    name: tangle-standalone.service
    state: stopped

- name: Bring chain spec
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: "{{ tangle_user_home }}/chainspecs/arana-local.json"
    dest: "{{ tangle_user_home }}/chainspecs/arana-local.json"
    owner: tangle
    mode: '0644'

- name: Purge chain
  become: true
  shell: |
    set -o pipefail
    {{ tangle_bin }} purge-chain -y --chain "{{ tangle_user_home }}/chainspecs/arana-local.json" --base-path {{ chain_data_dir }}  --database paritydb
  args:
    executable: /bin/bash
  changed_when: False

- name: Reinstall Tangle validator systemd unit file (validator node)
  template: src=tangle-validator-node.j2 dest=/etc/systemd/system/tangle-standalone.service
  become: true
  when: "'validator_node' in group_names"
  vars:
    peers: "{{ groups['validator_node'] }}"
  tags:
    validator-node-service

- name: Start validator service
  become: true
  systemd:
    name: tangle-standalone.service
    state: started
    daemon_reload: yes