
- name: stop tangle collator service
  become: true
  systemd:
    name: tangle-collator.service
    state: stopped

- name: bring chain spec
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: "{{ tangle_user_home }}/chainspecs/arana_testnet_raw.json"
    dest: "{{ tangle_user_home }}/arana_testnet_raw.json"
    owner: tangle
    mode: '0644'

- name: purge chain
  become: true
  shell: |
    set -o pipefail
    {{ dkg_bin }} purge-chain -y --chain "{{ tangle_user_home }}/arana_testnet_raw.json" --base-path {{ chain_data_dir }}  --database paritydb
  args:
    executable: /bin/bash
  changed_when: False

# - name: reinstall DKG systemd unit file (authority node)
#   template: src=dkg-authority-node.j2 dest=/etc/systemd/system/dkg.service
#   become: true
#   when: "'authority_node' in group_names"
#   vars:
#     peers: "{{ bootnodes }}"
#     authority: "{{ authority }}"
#   tags:
#     dkg-service

- name: reinstall Tangle collator systemd unit file (collator node)
  template: src=tangle-collator-node.j2 dest=/etc/systemd/system/tangle-collator.service
  become: true
  when: "'collator_node' in group_names"
  vars:
    peers: "{{ groups['collator_node'] }}"
  tags:
    collator-node-service

- name: start collator service
  become: true
  systemd:
    name: tangle-collator.service
    state: started
    daemon_reload: yes