
- name: Stop Tangle standalone service
  when: "'validator_node' in group_names"
  become: true
  systemd:
    name: tangle-standalone.service
    state: stopped

- name: Purge chain
  become: true
  when: "'validator_node' in group_names"
  shell: |
    set -o pipefail
    {{ tangle_bin }} purge-chain -y --chain "{{ tangle_user_home }}/chainspecs/arana-local.json" --base-path {{ chain_data_dir }}  --database paritydb-experimental
  args:
    executable: /bin/bash
  changed_when: False

- name: Reinstall Tangle systemd unit file (validator node)
  template: src=tangle-validator-node.j2 dest=/etc/systemd/system/tangle-standalone.service
  become: true
  when: "'validator_node' in group_names"
  vars:
    peers: "{{ groups['validator_node'] }}"
  tags:
    validator-node-service

# - name: start dkg service
#   when: "'validator_node' in group_names"
#   become: true
#   systemd:
#     name: dkg.service
#     state: started
#     daemon_reload: yes