
- name: stop Tangle collator service
  when: "'collator_node' in group_names"
  become: true
  systemd:
    name: tangle-collator.service
    state: stopped

- name: purge chain
  become: true
  when: "'collator_node' in group_names"
  shell: |
    set -o pipefail
    {{ tangle_bin }} purge-chain -y --chain "{{ tangle_user_home }}/arana_testnet_raw.json" --base-path {{ chain_data_dir }}  --database paritydb-experimental
  args:
    executable: /bin/bash
  changed_when: False

- name: reinstall DKG systemd unit file (collator node)
  template: src=dkg-collator-node.j2 dest=/etc/systemd/system/dkg.service
  become: true
  when: "'collator_node' in group_names"
  vars:
    peers: "{{ groups['collator_node'] }}"
  tags:
    collator-node-service

# - name: start dkg service
#   when: "'collator_node' in group_names"
#   become: true
#   systemd:
#     name: dkg.service
#     state: started
#     daemon_reload: yes