
- name: add Tangle group
  group:
    name: tangle
  become: true
  tags:
    system-accounts

- name: add Tangle user
  user:
    name: tangle
    comment: Tangle User
    group: tangle
  become: true
  tags:
    system-accounts

