
- name: Install tangle systemd unit file (validator node)
  template: src=tangle-validator-node.j2 dest=/etc/systemd/system/tangle-standalone.service
  become: true
  when: "'validator_node' in group_names"
  vars:
    peers: "{{ groups['validator_node'] }}"
  tags:
    validator-node-service
