
- name: Stop Tangle service
  become: true
  systemd:
    name: tangle-standalone.service
    state: stopped

- name: bring chain spec
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: "{{ dkg_user_home }}/chainspecs/arana-local.json"
    dest: "{{ dkg_user_home }}/chainspecs/arana-local.json"
    owner: dkg
    mode: '0644'

- name: Reinstall Tangle systemd unit file (validator node)
  template: src=tangle-validator-node.j2 dest=/etc/systemd/system/tangle-standalone.service
  become: true
  when: "'validator_node' in group_names"
  vars:
    peers: "{{ groups['authority_node'] }}"
  tags:
    tangle-validator-service

- name: start Tangle Node service
  become: true
  systemd:
    name: tangle-standalone.service
    state: started
    daemon_reload: yes