
- name: stop Tangle service
  become: true
  systemd:
    name: tangle-collator.service
    state: stopped

- name: bring chain spec
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: "{{ dkg_user_home }}/chainspecs/arana_testnet_raw.json"
    dest: "{{ dkg_user_home }}/arana_testnet_raw.json"
    owner: dkg
    mode: '0644'

- name: reinstall DKG systemd unit file (authority node)
  template: src=dkg-authority-node.j2 dest=/etc/systemd/system/tangle-collator.service
  become: true
  when: "'authority_node' in group_names"
  vars:
    peers: "{{ bootnodes }}"
    authority: "{{ authority }}"
  tags:
    tangle-node-service

- name: reinstall Tangle systemd unit file (collator node)
  template: src=dkg-collator-node.j2 dest=/etc/systemd/system/tangle-collator.service
  become: true
  when: "'collator_node' in group_names"
  vars:
    peers: "{{ groups['authority_node'] }}"
  tags:
    tangle-collator-service

- name: start Tangle Node service
  become: true
  systemd:
    name: tangle-collator.service
    state: started
    daemon_reload: yes