
- name: Stop Tangle service
  become: true
  systemd:
    name: tangle-collator.service
    state: stopped

- name: bring chain spec
  become: true
  ansible.builtin.copy:
    remote_src: true
    src: "{{ dkg_user_home }}/resources/testnet/template-local-raw.json"
    dest: "{{ dkg_user_home }}/resources/testnet/template-local-raw.json"
    owner: dkg
    mode: '0644'

- name: Reinstall Tangle systemd unit file (collator node)
  template: src=tangle-collator-node.j2 dest=/etc/systemd/system/tangle-collator.service
  become: true
  when: "'collator_node' in group_names"
  vars:
    peers: "{{ groups['authority_node'] }}"
  tags:
    tangle-collator-service

- name: start Tangle Node service
  become: true
  systemd:
    name: tangle-collator.service
    state: started
    daemon_reload: yes