---
 - name: Show Facts
   hosts: 
      - collator_node
   tasks:
    - name: Show substrate facts
      debug:
        var: ansible_local.substrate

    - name: check aura key
      uri:
        url: http://localhost:9933
        method: "POST"
        body_format: json
        body: |
            {
              "jsonrpc":"2.0",
              "id":1,
              "method":"author_hasKey",
              "params": [
                  "{{ aura_public_key }}",
                  "aura"
              ]
            }
      register: has_key
      until: has_key.status == 200
      retries: 10
      delay: 5

    - name: Verdict aura is
      debug:
        var: has_key

    
    - name: check wdkg key
      uri:
        url: http://localhost:9933
        method: "POST"
        body_format: json
        body: |
            {
              "jsonrpc":"2.0",
              "id":1,
              "method":"author_hasKey",
              "params": [
                  "{{ dkg_public_key }}",
                  "wdkg"
              ]
            }
      register: has_key
      until: has_key.status == 200
      retries: 10
      delay: 5

    - name: Verdict dkg is
      debug:
        var: has_key

    - name: check acco key
      uri:
        url: http://localhost:9933
        method: "POST"
        body_format: json
        body: |
            {
              "jsonrpc":"2.0",
              "id":1,
              "method":"author_hasKey",
              "params": [
                  "{{ acco_public_key }}",
                  "acco"
              ]
            }
      register: has_key
      until: has_key.status == 200
      retries: 10
      delay: 5

    - name: Verdict acco is
      debug:
        var: has_key