---
 - name: peek validator logs
   hosts: 
      - validator_node
   tasks:
      - name: peep validator logs
        shell: |
          set -o pipefail
          journalctl -u tangle-standalone --no-pager > /root/tangle.log
          tail -n 100 /root/tangle.log
        become: true
        args:
          executable: /bin/bash
        changed_when: False
        register: command_output

      - name: result
        debug:
          msg: "Command result: {{ command_output.stdout }}"

      - name: remove log
        file:
          path: /root/tangle.log
          state: absent