
- hosts:
    - collator_node
  tasks:
    - name: stop tangle collator service
      become: true
      systemd:
        name: tangle-collator.service
        state: stopped

    - name: start tangle collator service
      become: true
      systemd:
        name: tangle-collator.service
        state: started
        daemon_reload: yes
