
- hosts:
    - validator_node
  tasks:
    - name: stop tangle validator service
      become: true
      systemd:
        name: tangle-standalone.service
        state: stopped

    - name: start tangle validator service
      become: true
      systemd:
        name: tangle-standalone.service
        state: started
        daemon_reload: yes
