- hosts:
    - validator_node
  tasks:
    - name: stop tangle-standalone service
      become: true
      systemd:
        name: tangle-standalone.service
        state: stopped

    - include_role:
        name: chain_node
        tasks_from: build-chain.yml

    - name: start tangle validator service
      become: true
      systemd:
        name: tangle-standalone.service
        state: started
      
